services:
  - type: web
    name: buku-tamu-digital
    runtime: docker
    plan: free
    envVars:
      - key: APP_NAME
        value: "Buku Tamu Digital"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: aws-1-ap-northeast-2.pooler.supabase.com
      - key: DB_PORT
        value: "6543"
      - key: DB_DATABASE
        value: postgres
      - key: SESSION_DRIVER
        value: cookie
      - key: SESSION_LIFETIME
        value: "120"
      - key: CACHE_STORE
        value: array
      - key: QUEUE_CONNECTION
        value: sync
      - key: BCRYPT_ROUNDS
        value: "12"
      # Diisi manual di Render dashboard
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
